import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Toaster } from "@/components/ui/toaster";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      {/* <head>
        <script
          src={`https://maps.googleapis.com/maps/api/js?key=IzaSyA5ea5k0nS1yP7ntISTFU2OxFJi6pRsPSA&libraries=places`}
          async
          defer
        ></script>
      </head> */}
      <body className={inter.className}>
        <div className="min-h-screen">
          <Navbar />
          {children}
        </div>
        <Footer />
        <Toaster />
      </body>
    </html>
  );
}
